[package]
name = "aoc_2023"
version = "0.1.0"
edition = "2021"

[dependencies]
counter = "0.5.7"
itertools = "0.12.0"
nom = "7.1.3"
nom_locate = "4.2.0"
num = "0.4.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
